### ISSUE TITLE
Please remove "use 5.008001" in Makefile.PL

### ISSUE THREAD

**Issue by kentfredric** [ingydotnet/test-yaml-pm#2]
I'm trying to make it easier for people to have working CPAN::Reporter boxes on 5.6, and Test::YAML ( a dependency of YAML ) is right up there on the list of useful tools to do smoking with.

Test::YAML at present will pass its own tests and install without the `use ` declaration.

This is not a request for "support", merely a request to not stand in the way of people trying to make 5.6 work in a limited capacity ( But people who want 5.6 support can work out what needs to be done )

Thanks in advance.

**Comment by ingydotnet** [comment]
Done in 1.06. Does this mean I should do the same for YAML.pm?
